import { ChangeDetectionStrategy, Component, computed, inject, signal } from '@angular/core';
import { CurrencyPipe } from '@angular/common';
import { RouterLink } from '@angular/router';
import { ApiService } from '../core/api.service';
import { ReportingDashboard } from '../core/models';
import { SessionService } from '../core/session.service';

@Component({ imports:[RouterLink,CurrencyPipe],changeDetection:ChangeDetectionStrategy.OnPush,template:`<section class="backoffice"><div class="workspace-head"><div><p class="eyebrow">Tổng quan</p><h1>Dashboard quản trị</h1><p>Vai trò: <strong>{{session.roles().join(', ')}}</strong></p></div><a class="btn-primary" routerLink="/manager/pos">Mở POS</a></div>@if(loading()){<p>Đang lấy dữ liệu từ API…</p>}@else if(error()){<p class="error">{{error()}}</p>}@else{<div class="metric-grid"><article><span>Doanh thu 30 ngày</span><strong>{{revenue()|currency:'VND':'symbol':'1.0-0'}}</strong><small>Từ SQL Server</small></article><article><span>Đơn hàng online</span><strong>{{ordersCount()}}</strong><small>Dữ liệu đơn hiện có</small></article><article><span>Cảnh báo tồn thấp</span><strong>{{report()?.lowStock?.length??0}}</strong><small>Theo ngưỡng hệ thống</small></article></div><div class="panel"><h2>Sản phẩm bán chạy</h2>@for(item of report()?.bestSellers??[];track $index){<p>{{item.productName}} · {{item.variantName}} — {{item.quantitySold}}</p>}@empty{<p>Chưa có dữ liệu bán hàng trong kỳ.</p>}</div>}</section>`})
export class DashboardPageComponent {readonly api=inject(ApiService);readonly session=inject(SessionService);readonly report=signal<ReportingDashboard|null>(null);readonly ordersCount=signal(0);readonly loading=signal(true);readonly error=signal('');readonly revenue=computed(()=>this.report()?.revenue.reduce((sum,row)=>sum+row.revenue,0)??0);constructor(){this.api.reports().subscribe({next:value=>{this.report.set(value);this.api.managementOrders().subscribe({next:orders=>{this.ordersCount.set(orders.length);this.loading.set(false);},error:()=>this.loading.set(false)});},error:()=>{this.error.set('Không thể tải dashboard. Hãy đăng nhập Admin hoặc Manager.');this.loading.set(false);}});}}
